### ISSUE TITLE
Provide password via readline (or similar)

### ISSUE THREAD

**Issue by ccoenen** [eHealthAfrica/download-email-attachments#1]
Right now, my email password would appear either in the command line (and therefore its history).

many tools have a (parameterless) commant line argument (think `mysql -u user -p`) that will let you enter a password, without printing it.
In other cases (for scripting, for example) it is added as a "read password from that file over there" argument.

**Comment by lucidNTR** [comment]
@ccoenen the password should no longer be in the console log now.

**Comment by ccoenen** [comment]
awesome!
